/**
 * @author Vipin Joshi.
 * @since 09-12-2021.
 * @type {string} dashboard home screen action types.
 */
export const LOADING = '[DASHBOARD HOME] LOADING';
export const CATEGORY_LOADING = '[DASHBOARD HOME] CATEGORY_LOADING';
export const PRODUCT_LOADING = '[DASHBOARD HOME] PRODUCT_LOADING';
export const CUSTOMER_LOADING = '[DASHBOARD HOME] CUSTOMER_LOADING';
export const PAYMENT_METHODS_LOADING = '[DASHBOARD HOME] PAYMENT_METHODS_LOADING';
export const ERROR = '[DASHBOARD HOME] ERROR';
export const SUCCESS = '[DASHBOARD HOME] SUCCESS';
export const SET_TAX_LIST = '[DASHBOARD HOME] SET_TAX_LIST';
export const SET_UOM_LIST = '[DASHBOARD HOME] SET_UOM_LIST';
export const SET_PRODUCTS = '[DASHBOARD HOME] SET_PRODUCTS';
export const SET_PRODUCT_CATEGORIES = '[DASHBOARD HOME] SET_PRODUCT_CATEGORIES';
export const FILTER_PRODUCTS = '[DASHBOARD HOME] FILTER_PRODUCTS';
export const ADD_PRODUCT_TO_CART = '[DASHBOARD HOME] ADD_PRODUCT_TO_CART';
export const SET_CART_PRODUCTS = '[DASHBOARD HOME] SET_CART_PRODUCTS';
export const CLEAR_PRODUCT_CART = '[DASHBOARD HOME] CLEAR_PRODUCT_CART';
export const HOLD_PRODUCT_CART = '[DASHBOARD HOME] HOLD_PRODUCT_CART';
export const SELECT_CART_PRODUCT = '[DASHBOARD HOME] SELECT_CART_PRODUCT';
export const SELECT_CART_FEATURE_ACTION = '[DASHBOARD HOME] SELECT_CART_FEATURE_ACTION';
export const SHOW_AVAILABLE_PRODUCT_DISCOUNT_DIALOG = '[DASHBOARD HOME] SHOW_AVAILABLE_PRODUCT_DISCOUNT_DIALOG';
export const SET_AVAILABLE_PRODUCT_DISCOUNT = '[DASHBOARD HOME] SET_AVAILABLE_PRODUCT_DISCOUNT';
export const PRESS_CART_FEATURE_NUMERIC_KEY = '[DASHBOARD HOME] PRESS_CART_FEATURE_NUMERIC_KEY';
export const PRESS_CART_FEATURE_DELETE_KEY = '[DASHBOARD HOME] PRESS_CART_FEATURE_DELETE_KEY';
export const REMOVE_CART_PRODUCT_DISCOUNT = '[DASHBOARD HOME] REMOVE_CART_PRODUCT_DISCOUNT';
export const APPLY_CART_PRODUCT_DISCOUNT = '[DASHBOARD HOME] APPLY_CART_PRODUCT_DISCOUNT';
export const PRESS_PRODUCT_CATEGORY_BREADCRUMB = '[DASHBOARD HOME] PRESS_PRODUCT_CATEGORY_BREADCRUMB';
export const PRESS_PRODUCT_CATEGORY = '[DASHBOARD HOME] PRESS_PRODUCT_CATEGORY';
export const SET_TOTAL_CART_PRICE = '[DASHBOARD HOME] SET_TOTAL_CART_PRICE';
export const SET_TOTAL_CART_DISCOUNT_PRICE = '[DASHBOARD HOME] SET_TOTAL_CART_DISCOUNT_PRICE';
export const RESET_REDUCER_STATE_FOR_NEW_ORDER = '[DASHBOARD HOME] RESET_REDUCER_STATE_FOR_NEW_ORDER';
export const SET_COMPLIMENTARY = '[DASHBOARD HOME] SET_COMPLIMENTARY';
export const SET_FAVOURITE_PRODUCTS = '[DASHBOARD HOME] SET_FAVOURITE_PRODUCTS';
export const ENABLE_FAVOURITE_PRODUCTS = '[DASHBOARD HOME] ENABLE_FAVOURITE_PRODUCTS';
export const FILTER_FAVOURITE_PRODUCTS = '[DASHBOARD HOME] FILTER_FAVOURITE_PRODUCTS';
export const SET_LIMIT_50 = '[DASHBOARD HOME] SET_LIMIT_50';
export const SET_PURPOSE = '[DASHBOARD HOME] SET_PURPOSE';
export const RESET_PURPOSE = '[DASHBOARD HOME] RESET_PURPOSE';
export const SHOW_PURPOSE_DIALOG = '[DASHBOARD HOME] SHOW_PURPOSE_DIALOG';
export const SHOW_PURPOSE_SELECTION_DIALOG = '[DASHBOARD HOME] SHOW_PURPOSE_SELECTION_DIALOG';
export const SET_FARM_DETAILS = '[DASHBOARD HOME] SET_FARM_DETAILS';
export const RESET_FARM_DETAILS = '[DASHBOARD HOME] RESET_FARM_DETAILS';
export const ON_SELECT_GENERAL_PURPOSE = '[DASHBOARD HOME] ON_SELECT_GENERAL_PURPOSE';


