/**
* Webkul Software.
*
* @category Webkul
* @package Webkul_Mobikul_Odoo_Pos
* @author Webkul
* @copyright Copyright (c) WebkulSoftware Private Limited (https://webkul.com)
* @license https://store.webkul.com/license.html
*
*/

export const StorageKeyConstants = {
    ITEMS_PER_PAGE_COUNT:"ITEMS_PER_PAGE_COUNT",
    AGENT_LOGIN_HEADER:"AGENT_LOGIN_HEADER",

    AGENT_TIME_ZONE:"AGENT_TIME_ZONE",
    AGENT_LANG:"AGENT_LANG",
    AGENT_USER_ID:"AGENT_USER_ID",
    AGENT_NAME:"AGENT_NAME",
    IS_LOGGED_IN:"IS_LOGGED_IN",
    AGENT_AGENT_ID:"AGENT_AGENT_ID",
    AGENT_PROFILE_IMAGE:"AGENT_PROFILE_IMAGE",
    AGENT_EMAIL: "AGENT_EMAIL",

    SESSION_CONFIG_SHOP_ID: "SESSION_CONFIG_SHOP_ID",
    SESSION_CONFIG_SHOP_NAME: "SESSION_CONFIG_SHOP_NAME",
    SESSION_CONFIG_SHOP_SHORT_NAME: "SESSION_CONFIG_SHOP_SHORT_NAME",
    SESSION_CONFIG_SESSION_ID: "SESSION_CONFIG_SESSION_ID",
    SESSION_CONFIG_LOGIN_NUMBER: "SESSION_CONFIG_LOGIN_NUMBER",
    SESSION_CONFIG_CURRENCY_OBJECT_STRING: "SESSION_CONFIG_CURRENCY_OBJECT_STRING",
    SESSION_CONFIG_RECEIPT_HEADER: "SESSION_CONFIG_RECEIPT_HEADER",
    SESSION_CONFIG_TO_INVOICE: "SESSION_CONFIG_TO_INVOICE",
    SESSION_CONFIG_RECEIPT_FOOTER: "SESSION_CONFIG_RECEIPT_FOOTER",
    SESSION_CONFIG_SESSION_START_AT: "SESSION_CONFIG_SESSION_START_AT",
    SESSION_POS_CONFIG: "SESSION_POS_CONFIG",
    SESSION_CONFIG_NORMAL_SEQUENCE_NO: "SESSION_CONFIG_NORMAL_SEQUENCE_NO",
    SESSION_CONFIG_COMPLEMENT_SEQUENCE_NO: "SESSION_CONFIG_COMPLEMENT_SEQUENCE_NO",
}
