/**
 * @author Vipin Joshi.
 * @since 12-01-2022.
 * @type {string} Payment screen action types.
 */
export const LOADING = '[PAYMENT] LOADING';
export const ERROR = '[PAYMENT] ERROR';
export const SUCCESS = '[PAYMENT] SUCCESS';
export const SET_DISCOUNT_REMARKS = '[PAYMENT] SET_DISCOUNT_REMARKS';
export const SET_PURPOSE = '[PAYMENT] SET_PURPOSE';
export const SET_PAYMENT_METHODS = '[PAYMENT] SET_PAYMENT_METHODS';
export const ON_PRESS_PAYMENT_METHOD = '[PAYMENT] ON_PRESS_PAYMENT_METHOD';
export const SET_USED_PAYMENT_METHODS = '[PAYMENT] SET_USED_PAYMENT_METHODS';
export const SET_COLLECTED_AMOUNT = '[PAYMENT] SET_COLLECTED_AMOUNT';
export const SET_TOTAL_COLLECTED_AMOUNT = '[PAYMENT] SET_TOTAL_COLLECTED_AMOUNT';
export const SET_TOTAL_CART_AMOUNT = '[PAYMENT] SET_TOTAL_CART_AMOUNT';
export const SET_TOTAL_CART_APPLIED_DISCOUNT_AMOUNT = '[PAYMENT] SET_TOTAL_CART_APPLIED_DISCOUNT_AMOUNT';
export const SELECT_USED_PAYMENT_METHOD = '[PAYMENT] SELECT_USED_PAYMENT_METHOD';
export const DELETE_USED_PAYMENT_METHOD = '[PAYMENT] DELETE_USED_PAYMENT_METHOD';
export const ON_USED_PAYMENT_METHOD_DETAIL_DIALOG_BACK_PRESS = '[PAYMENT] ON_USED_PAYMENT_METHOD_DETAIL_DIALOG_BACK_PRESS';
export const ON_USED_PAYMENT_METHOD_DETAIL_DIALOG_SUBMIT_PRESS = '[PAYMENT] ON_USED_PAYMENT_METHOD_DETAIL_DIALOG_SUBMIT_PRESS';
export const SET_INVOICE_ORDER = '[PAYMENT] SET_INVOICE_ORDER';
export const SET_CAN_MAKE_PAYMENT = '[PAYMENT] SET_CAN_MAKE_PAYMENT';
