/**
 * @author Vipin Joshi.
 * @since 04-01-2022.
 * @type {string} Customer screen action types.
 */
export const LOADING = '[CUSTOMER] LOADING';
export const ERROR = '[CUSTOMER] ERROR';
export const SUCCESS = '[CUSTOMER] SUCCESS';
export const SET_CUSTOMERS = '[CUSTOMER] SET_CUSTOMERS';
export const SET_SEARCH = '[CUSTOMER] SET_SEARCH';
export const SET_CUSTOMER_DISPLAY_KEYS = '[CUSTOMER] SET_CUSTOMER_DISPLAY_KEYS';
export const SET_COUNTRIES = '[CUSTOMER] SET_COUNTRIES';
export const SET_STATES = '[CUSTOMER] SET_STATES';
export const SELECT_CUSTOMER = '[CUSTOMER] SELECT_CUSTOMER';
export const DESELECT_CUSTOMER = '[CUSTOMER] DESELECT_CUSTOMER';
export const SET_CREATED_CUSTOMER = '[CUSTOMER] SET_CREATED_CUSTOMER';
export const RESET_REDUCER_STATE_FOR_NEW_ORDER = '[CUSTOMER] RESET_REDUCER_STATE_FOR_NEW_ORDER';
